XTeam\HighFiveSlackBundle\Entity\Channel:
    type: entity
    table: null
    repositoryClass: XTeam\HighFiveSlackBundle\Entity\ChannelRepository
    id:
        id:
            type: string
            id: true
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        highFives:
            targetEntity: HighFive
            mappedBy: channel
    lifecycleCallbacks: {  }
