XTeam\HighFiveSlackBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: XTeam\HighFiveSlackBundle\Entity\UserRepository
    id:
        id:
            type: string
            id: true
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        highFives:
            targetEntity: HighFive
            mappedBy: publisher
    lifecycleCallbacks: {  }
